// components/kpi_data.jsx
export const kpiData = [
    {
      mainLabel: 'Sell Out Volume',
      subLabel: '',
      value: '348,940K',
      yoyLabel: 'YoY: -67,201K (-12.85%)',
      change: -12.85,
      mdlzValue: '144,077K',
      mdlzYoyChange: 'YoY: -28,195K (-13.43%)',
      mdlzIsPositive: false,
      mdlzLabel: 'Volume (Mdlz)',
    },
    {
      mainLabel: 'Sell Out Value',
      subLabel: '',
      value: 'R$302,631K',
      yoyLabel: 'YoY: -R$56,410K (-7.70%)',
      change: -7.70,
      mdlzValue: 'R$148,194K',
      mdlzYoyChange: 'YoY: -R$28,335K (-10.20%)',
      mdlzIsPositive: false,
      mdlzLabel: 'Value (Mdlz)',
    },
    {
      mainLabel: 'Sell Out Units',
      subLabel: '',
      value: '297,284K',
      yoyLabel: 'YoY: -57,627K (-12.34%)',
      change: -12.34,
      mdlzValue: '140,089K',
      mdlzYoyChange: 'YoY: -27,339K (-13.82%)',
      mdlzIsPositive: false,
      mdlzLabel: 'Units (Mdlz)',
    },
    {
      mainLabel: 'Avg Price Per Unit',
      subLabel: '',
      value: 'R$1.02',
      yoyLabel: 'YoY: +R$0.98 (5.30%)',
      change: 5.30,
      mdlzValue: 'R$1.06',
      mdlzYoyChange: 'YoY: +R$1.04 (4.21%)',
      mdlzIsPositive: true,
      mdlzLabel: 'Avg Price (Mdlz)',
    },
  ];